inherit_from: .rubocop_ruby_and_erb.yml

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: true
  EnabledMethods:
    - scenario
    - xscenario

FactoryBot/AttributeDefinedStatically:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/LineLength:
  Max: 110
  Severity: refactor

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true
  Exclude:
    - "db/migrate/201[5-8]*"
    - "db/migrate/*install_audited.rb"

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - find_by_slug_or_id
    - find_by_slug_or_id!
    - find_by_manager_login

Rails/EnumUniqueness:
  Enabled: true

Rails/FindBy:
  Enabled: true
  Include:
    - "**/*.rb"

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true
  Severity: refactor

Rails/InverseOf:
  Enabled: true
  Exclude:
    - "app/models/related_content.rb"

Rails/NotNullColumn:
  Enabled: true
  Exclude:
    - "db/migrate/201[5-7]*"

Rails/OutputSafety:
  Enabled: true
  Severity: warning
  Exclude:
    - app/helpers/text_with_links_helper.rb
    - config/initializers/escape_javascript_fix.rb

Rails/PluralizationGrammar:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SaveBang:
  Enabled: true
  Severity: refactor

Rails/SkipsModelValidations:
  Enabled: true
  Blacklist:
    - update_attribute
  Exclude:
    - lib/acts_as_paranoid_aliases.rb

Rails/Validation:
  Enabled: true

RSpec/AroundBlock:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

RSpec/EmptyExampleGroup:
  Enabled: true
  Exclude:
    - spec/factories/**/*

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true
  Exclude:
    - spec/factories/**/*

RSpec/ExampleWording:
  Enabled: true

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true
  Exclude:
    - spec/controllers/concerns/has_filters_spec.rb
    - spec/controllers/concerns/has_orders_spec.rb

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/NotToNot:
  Enabled: true

RSpec/OverwritingSetup:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/ScatteredLet:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/VoidExpect:
  Enabled: true
